config/routes.rb
Strahlen::Application.routes.draw do

  root 'static_pages#home'

  match 'info' => 'static_pages#info', via: :get
  match 'story' => 'static_pages#story', via: :get
  match 'privacy' => 'static_pages#privacy', via: :get
  match 'faqs' => 'static_pages#faqs', via: :get
  match 'terms' => 'static_pages#terms', via: :get
  match 'campaign' => 'static_pages#info',  via: :get

  match 'hide_opt_in' => 'customers#hide_optin_bar', via: :get

  resource :customers

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :email, presence: true

  before_save :sanitize_fields

  def sanitize_fields
    self.email = self.email.strip.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def create
    @customer = Customer.new(customer_params)

    begin
      @saved = @customer.save
      cookies[:hide_optin] = { :value => "true"}
    rescue

    end
  end

  def hide_optin_bar
    cookies[:hide_optin] = { :value => "true", :expires => Time.now + 3600}
  end

  private
  def customer_params
    params.require(:customer).permit(:email)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def info
  end

  def story
  end

  def faqs
  end

  def privacy
  end

  def terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def facebook_link
    'https://www.facebook.com/strahlenlights'
  end

  def twitter_link
    'https://twitter.com/strahlenlights'
  end

  def google_plus_link
    'https://plus.google.com/+Strahlenlights/posts'
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/customers/create.js.erb
<% if @saved == true  %>
    Strahlen.removeEmailBar();
<% else %>
    alert('The email you entered is not valid');
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="col-md-12">
    <div class="row" style="margin-top: 60px">
      <div class="col-md-2 col-md-offset-5">
        <div class="row">

          <div class="col-xs-4 text-center"><%= link_to(fa_icon('facebook'), facebook_link, :target => '_blank') %></div>
          <div class="col-xs-4 text-center"><%= link_to(fa_icon('twitter'), twitter_link, :target => '_blank') %></div>
          <div class="col-xs-4 text-center"><%= link_to(fa_icon('google-plus'), google_plus_link, :target => '_blank') %></div>
        </div>
      </div>
    </div>



    <div class="row">
      <div class="col-md-8 col-md-offset-2 divider-row">
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <ul class="list-inline">
          <li><%= link_to('FAQ', faqs_path) %></li>
          <li><%= link_to('Privacy Policy', privacy_path) %></li>
          <li><%= link_to('Terms and Conditions', terms_path) %></li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center copyright">
        &copy; <%= Time.now.year %> Strahlen LLC.
      </div>
    </div>

  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div id="nav-container">

  <% if cookies[:hide_optin].blank?  %>
       <section id="opt-in-container">
    <div>
        <div class="row">
          <div class="col-md-12 text-center">
            Get the latest updates on Strahlen!

            <%= form_for(Customer.new, :remote => true, html: {class: 'form-inline', style: 'display:inline-block; margin-left:20px'}) do |f| %>
              <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <%= f.text_field :email, type: :email, class: 'form-control', placeholder: 'Email Address' %>
              </div>
              <button type="submit" class="btn btn-default">Sign Up</button>
            <% end %>


            <button type="button" class="close" id="close-email-input" aria-hidden="true" style="font-size: 40px">&times;</button>
          </div>
        </div>
    </div>
  </section>
  <% end %>

  <div>
    <nav class="navbar navbar-inverse navbar-default" role="navigation">
      <div class="navbar-header">
        <%= link_to(image_tag('navLogo.png', :class => 'img-responsive', :style =>'max-height:35px'), root_path, :class => 'navbar-brand', :style => 'padding:0; padding-top:7px') %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to('The Strahlen Story', story_path) %> </li>
          <li><%= link_to(fa_icon('facebook'), facebook_link, :target => '_blank') %> </li>
          <li><%= link_to(fa_icon('twitter'), twitter_link, :target => '_blank') %></li>
          <li><%= link_to(fa_icon('google-plus'), google_plus_link, :target => '_blank') %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </div>

  <section id="sub-nav-container">
    <div>
      <% if content_for(:additional_nav) %>
          <%= yield(:additional_nav) %>
      <% end %>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Strahlen | High Efficiency, Affordable LED lighting for Photographers and Filmmakers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="description" content="High Efficiency, Affordable LED lighting for Photographers and Filmmakers">
  <link rel="author" href="https://plus.google.com/+Strahlenlights/" />

  <meta property="og:title" content="Strahlen LED Lighting"/>
  <meta property="og:type" content="website"/>
  <meta property="og:image" content="<%= image_url('carousel5.jpg') %>"/>
  <meta property="og:url" content="http://www.strahlenlights.com"/>
  <meta property="og:description" content="High Efficiency, Affordable LED lighting for Photographers and Filmmakers"/>

  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body style="position: relative" data-spy="scroll" data-target="#feature-nav" data-offset="255">

    <%= render :partial => 'layouts/navbar' %>

    <section id="body-container">
      <div>
        <%= yield %>
      </div>
    </section>

    <%= render :partial => 'layouts/footer' %>


</body>
</html>

app/views/static_pages/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="6000">
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1" class=""></li>
    <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
    <li data-target="#carousel-example-generic" data-slide-to="3" class=""></li>
    <li data-target="#carousel-example-generic" data-slide-to="4" class=""></li>
    <li data-target="#carousel-example-generic" data-slide-to="5" class=""></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag('carousel/carousel_01.jpg') %>
    </div>
    <div class="item">
      <%= image_tag('carousel/carousel_02.jpg') %>
    </div>
    <div class="item">
      <%= image_tag('carousel/carousel_03.jpg') %>
    </div>
    <div class="item">
      <%= image_tag('carousel/carousel_04.jpg') %>
    </div>
    <div class="item">
      <%= image_tag('carousel/carousel_05.jpg') %>
    </div>
    <div class="item">
      <%= image_tag('carousel/carousel_06.jpg') %>
    </div>
  </div>
</div>

app/views/static_pages/_specs.html.erb
<div class="modal fade" id="specs-modal" tabindex="-1" role="dialog" aria-labelledby="specs-modal-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="specs-modal-label">ST-100 Specs</h4>
      </div>
      <div class="modal-body" id="specs-container" style="padding-left: 0; padding-right: 0">
        <div class="row">
          <div class="col-xs-5">
            Power Consumption:
          </div>
          <div class="col-xs-7">
            100W
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Color Rendering Index:
          </div>
          <div class="col-xs-7">
            90
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Color Temperature:
          </div>
          <div class="col-xs-7">
            Tungsten | Daylight | Bi-Color
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Beam Angle:
          </div>
          <div class="col-xs-7">
            110 degrees
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Lifespan:
          </div>
          <div class="col-xs-7">
            50,000 hours
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Built in Mounts:
          </div>
          <div class="col-xs-7">
            Bowens S-type<br>
            3” Magnetic Attachment
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Additional Mount:
          </div>
          <div class="col-xs-7">
             Chimera 6.5”
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Light Mount:
          </div>
          <div class="col-xs-7">
            Baby mount (5/8")
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Dimming Range:
          </div>
          <div class="col-xs-7">
            10-100%
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Noise Output:
          </div>
          <div class="col-xs-7">
            18 dBa
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Size:
          </div>
          <div class="col-xs-7">
            16.5" x 7.5" x 5.5"
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Weight:
          </div>
          <div class="col-xs-7">
            5.8lbs
          </div>
        </div>

        <div class="row">
          <div class="col-xs-5">
            Power Input:
          </div>
          <div class="col-xs-7">
            90-305V AC, 47-63Hz
          </div>
        </div>

        <div class="row" style="margin-bottom: 20px">
          <div class="col-xs-5">
            Warranty:
          </div>
          <div class="col-xs-7">
            One year limited
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 text-center">
            <h4 style="margin-top: 20px; margin-bottom: 10px">Foot-candle output (Tungsten - open face)</h4>
            <%= image_tag('specs/tungsten_foot_candles.png', class: 'img-responsive') %>
            <h4 style="margin-top: 20px; margin-bottom: 10px">Foot-candle output (Daylight - open face)</h4>
            <%= image_tag('specs/daylight_foot_candles.png', class: 'img-responsive') %>
            <h4 style="margin-top: 20px; margin-bottom: 10px">Colorimetry (Tungsten & Daylight)</h4>
            <%= image_tag('specs/colorimetry.jpg', class: 'img-responsive', :style => 'width:100%') %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/static_pages/faqs.html.erb
<div id="static_page_container" style="margin-top: 100px; min-height: 600px">
  <section class="container-fluid titleContainer" >
    <div class="row-fluid">
      <div class="span12 text-center titleText">
        <h1>FAQS</h1>
      </div>
    </div>
  </section>

  <section class="container-fluid">
    <div class="row-fluid">

      <div class="span12 bodyText text-center" style="padding:30px">
        <h1><strong>Coming Soon...</strong></h1>
        In the meantime, send as an email at <a href="mailto:info@strahlenlights.com" style="color: #333">info@strahlenlights.com</a>.

        <br><br><br><br><br><br><br><br><br><br>


      </div>
    </div>
  </section>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-9">
    <div class="row section-container">
      <div class="box-shadow"></div>
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-5">

            <div class="row">
              <div class="col-xs-12 product-title-text">
                <div style="font-size: 100px; line-height: 65px; margin-top: 15%; padding-right: 20px">ST-100</div>
              </div>
            </div>

            <div class="row" style="margin-top: -15px">
              <div class="col-xs-12" style="font-size: 19px">
                <div>Unparalleled Versatility and Quality</div>
              </div>
            </div>

            <div class="row" style="margin-top: 80px">
              <div class="col-xs-12" style="font-size: 22px; font-family: proxima_nova-semibold">
                Buy now on IndieGoGo!
              </div>
            </div>

            <div class="row" style="margin-top: 15px">
              <div class="col-xs-12">
                <a href="http://igg.me/at/strahlenlights/x/5621587" class="btn btn-warning" style="font-size: 15px">Buy the ST-100 on IndieGoGo</a>
              </div>
            </div>

            <div class="row" style="margin-top: 15px; margin-bottom: 15px">
              <div class="col-xs-12">
                <a href="/info" class="btn btn-default" style="font-size: 15px">Learn More About the ST-100</a>
              </div>
            </div>
          </div>

          <div class="col-md-7">
            <%= render :partial => 'static_pages/carousel' %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12" style="min-height: 112px">

          </div>
        </div>

      </div>

    </div>

  </div>
  <div class="col-md-3 text-right" style="padding-right: 0">
      <iframe src="http://www.indiegogo.com/project/604340/widget/5621587" width="224px" height="486px" frameborder="0" scrolling="no"></iframe>
  </div>
</div>





<br><br>

<div class="row" style="margin-left: -15px; margin-right:-15px">
  <div class="col-md-3">
    <div class="section-container box-shadow">
      <%= link_to(image_tag('home_bottom/strahlen_home_bottom_01.jpg', :class => 'img-responsive'), info_path(:anchor => 'led_technology') ) %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="section-container box-shadow">
        <%= link_to(image_tag('home_bottom/strahlen_home_bottom_02.jpg', :class => 'img-responsive'),  info_path(:anchor => 'creative_flexibility'))%>
    </div>
  </div>
  <div class="col-md-3">
    <div class="section-container box-shadow">
      <%= link_to(image_tag('home_bottom/strahlen_home_bottom_03.jpg', :class => 'img-responsive'), info_path(:anchor => 'built_to_last') ) %>
    </div>
  </div>
  <div class="col-md-3">
    <div class="section-container box-shadow">
        <%= link_to(image_tag('home_bottom/strahlen_home_bottom_04.jpg', :class => 'img-responsive'), info_path(:anchor => 'integrated_design') ) %>
    </div>
  </div>
</div>


<br><br>

app/views/static_pages/info.html.erb
<% content_for :additional_nav do %>
    <div class="row">
      <div class="col-md-12 section-container" style="margin-top: 20px">
        <div class="box-shadow"></div>
        <div class="row">
          <div class="col-md-4 product-title-text">
            <div>
                ST-100
            </div>
          </div>
          <div class="col-md-8 text-right product-specs">
            <button class="btn btn-warning" data-toggle="modal" data-target="#specs-modal" style="font-size: 18px">Just the specs</button>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
            <nav class="navbar navbar-default navbar-static-top center" role="navigation" id="feature-nav">
              <div class="collapse navbar-collapse text-center">
                <ul class="nav navbar-nav">
                  <li class="active"><a href="#led_technology">LED Technology</a></li>
                  <li><a href="#industry_standard">Industry Standard</a></li>
                  <li><a href="#creative_flexibility">Creative Flexibility</a></li>
                  <li><a href="#built_to_last">Built to Last</a></li>
                  <li><a href="#integrated_design">Integrated Design</a></li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
<% end %>




  <section id="feature-list-section" >
    <div class="row section-container" style="margin-bottom: 50px; background-color: #fff">
      <div class="box-shadow"></div>
      <div class="col-md-12 text-center" style="padding-bottom: 15px">
        <%= image_tag('info_page/header.jpg', :class => 'img-responsive') %>
      </div>
    </div>
  </section>



  <section class="row section-container" style="margin-bottom: 50px">
    <div class="box-shadow"></div>
    <div class="col-md-12">




    <div class="row off-white" id="led_technology" style="min-height: 452px" >
      <div class="col-md-6 no-padding">
        <%= image_tag('info_page/info_01.jpg', class: 'img-responsive') %>
      </div>
      <div class="col-md-6" style="padding-top: 40px">
        <h1>LED Technology</h1>
        <h2>Quality you can see</h2>
        <br>
        With over 9000 lumens and a CRI of 90, it's easy to see what separates the ST-100 from other LED lights.
        <br><br>

        <div class="row">
          <div class="col-xs-6">
            <div class="row">
              <div class="col-xs-4 border-right led-spec-col">
                <div class="row">
                  <div class="col-xs-12">
                    100
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    Watts
                  </div>
                </div>

              </div>
              <div class="col-xs-3 border-right led-spec-col">
                <div class="row">
                  <div class="col-xs-12">
                    90
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    CRI
                  </div>
                </div>
              </div>
              <div class="col-xs-4  led-spec-col">
                <div class="row">
                  <div class="col-xs-12">
                    +9000
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    Lumens
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


        <br><br>

        <div class="row">
          <div class="col-xs-6">
            <table>
                <tr>
                  <td></td>
                  <td>4ft</td>
                  <td>8ft</td>
                  <td>12ft</td>
                </tr>
                <tr>
                  <td>Lux:</td>
                  <td>1630</td>
                  <td>470</td>
                  <td>230</td>
                </tr>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="row odd" id="industry_standard"  style="min-height: 322px">
      <div class="col-md-6" style="padding-top: 40px; padding-right: 0px">
        <h1>Industy Standard</h1>
        <h2>The same old, updated</h2>
        <br>
        Moving to LEDs doesn't mean you lose your standard color temperatures or quality.
        The ST-100 includes tungsten- and daylight-balanced models, as well as a bi-color option.
      </div>
      <div class="col-md-6 no-padding text-right">
        <%= image_tag('info_page/info_02.jpg', class: 'img-responsive') %>
      </div>
    </div>


    <div class="row off-white" id="creative_flexibility" style="min-height: 386px">
      <div class="col-md-6 no-padding">
        <%= image_tag('info_page/info_03.jpg', class: 'img-responsive') %>
      </div>
      <div class="col-md-6" style="padding-top: 40px">
        <h1>Creative Flexibility</h1>
        <h2>Let freedom reign</h2>
        <br>
        Softboxes, reflectors, barn doors, snoots, gels, bare bulb, open face - you name it, the ST-100 can handle it.
        Let your creativity run free with unbeatable flexibility and control.
        <br><br>


        <div class="row">
            <div class="col-xs-12">
                <div class="row">
                  <div class="col-xs-3 creative-col">
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        S-type
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        Mount
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-4 creative-col">
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        10-100%
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        Dimmable
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-5 creative-col">
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        Flicker-free
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-xs-12 text-center">
                        No Color Shift
                      </div>
                    </div>
                  </div>
                </div>
            </div>
        </div>
      </div>
    </div>


    <div class="row odd" id="built_to_last" style="min-height: 403px">
      <div class="col-md-6" style="padding-top: 40px">
        <h1>Built to Last</h1>
        <h2>All-aluminum. All ready to go.</h2>
        <br>
        A combination of sturdy and lightweight aluminum and silent,
        active cooling give you confidence in knowing the ST-100 is ready for even the toughest environments.<br>
        <br>

        <div class="row">
          <div class="col-xs-8">
            <div class="row">
              <div class="col-xs-4 built-spec-col">
                <div class="row">
                  <div class="col-xs-12">
                    5.8
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12">
                    pounds
                  </div>
                </div>
              </div>
              <div class="col-xs-5 text-center" style="padding-left: 0; padding-right: 0">
                <div class="text-left" style="display: inline-block">
                  <div>L 16.5"</div>
                  <div>W 7.5"</div>
                  <div>H 5.5"</div>
                </div>
              </div>
              <div class="col-xs-3 built-spec-col" style="padding-left: 0">
                <div class="row">
                  <div class="col-xs-12 text-center">
                    18
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-12 text-center">
                    dBa
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="col-md-6 no-padding text-right">
        <%= image_tag('info_page/info_04.jpg', class: 'img-responsive') %>
      </div>
    </div>

    <div class="row off-white" id="integrated_design" style="min-height: 306px">
      <div class="col-md-6 no-padding">
        <%= image_tag('info_page/info_05.jpg', class: 'img-responsive') %>
      </div>
      <div class="col-md-6" style="padding-top: 40px">
        <h1>Integrated Design</h1>
        <h2>Making your life easy</h2>
        <br>
        The ST-100 is entirely self-contained and utilizes a standard AC power port - eliminating the need
        to carry around a separate proprietary power supply.
      </div>
    </div>

    </div>
  </section>

  </section>

<%= render :partial => 'static_pages/specs' %>

app/views/static_pages/privacy.html.erb
<div id="static_page_container" style="margin-top: 100px">

  <section class="container-fluid titleContainer">
    <div class="row-fluid">
      <div class="span12 text-center titleText">
        <h1>Privacy Policy</h1>
      </div>
    </div>
  </section>

  <section class="container-fluid">
    <div class="row-fluid">

      <div class="span12 bodyText" style="padding:30px">
        <br><br>

        <strong>What information do we collect?</strong><br>
        We collect information from you when you place an order or subscribe to our newsletter.<br><br>

        When ordering or registering on our site, as appropriate, you may be asked to enter your: name, e-mail address, mailing address, phone number or credit card information. You may, however, visit our site anonymously.
        <br><br>
        <strong>What do we use your information for?</strong><br>
        Any of the information we collect from you may be used in one of the following ways:
        <br><br>
        -To improve our website<br>
        (we continually strive to improve our website offerings based on the information and feedback we receive from you)
        <br><br>
        -To improve customer service<br>
        (your information helps us to more effectively respond to your customer service requests and support needs)
        <br><br>
        -To process transactions<br>
        Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested.
        <br><br>
        -To administer a contest, promotion, survey or other site feature
        <br><br>
        -To send periodic emails<br>
        The email address you provide for order processing, may be used to send you information and updates pertaining to your order, in addition to receiving occasional company news, updates, related product or service information, etc.
        Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.
        <br><br>
        <strong>How do we protect your information?</strong><br>
        We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information.
        <br><br>
        We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential.
        <br><br>
        After a transaction, your private information (credit cards, financials, etc.) will not be stored on our servers.
        <br><br>
        <strong>Do we use cookies?</strong><br>
        Yes (Cookies are small files that a site or its service provider transfers to your computers hard drive through your Web browser (if you allow) that enables the sites or service providers systems to recognize your browser and capture and remember certain information
        <br><br>
        We use cookies to help us remember and process the items in your shopping cart, understand and save your preferences for future visits and compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.
        <br><br>
        <strong>Do we disclose any information to outside parties?</strong><br>
        We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.
        <br><br>
        <strong>Third party links</strong><br>
        Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.
        <br><br>
        <strong>California Online Privacy Protection Act Compliance</strong><br>
        Because we value your privacy we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act. We therefore will not distribute your personal information to outside parties without your consent.
        <br><br>
        <strong>Childrens Online Privacy Protection Act Compliance</strong><br>
        We are in compliance with the requirements of COPPA (Childrens Online Privacy Protection Act), we do not collect any information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.
        <br><br>
        <strong>Your Consent</strong><br>
        By using our site, you consent to our privacy policy.
        <br><br>
        <strong>Changes to our Privacy Policy</strong><br>
        If we decide to change our privacy policy, we will post those changes on this page.<br><br>

        info@strahlenlights.com
      </div>
    </div>
  </section>


</div>